language: go

sudo: false

go:
  - 1.7
  - 1.8
  - tip

before_install:
  - mkdir -p $HOME/gopath/src/github.com/aframevr/slackoverflow
  - rsync -az ${TRAVIS_BUILD_DIR}/ $HOME/gopath/src/github.com/aframevr/slackoverflow/
  - export TRAVIS_BUILD_DIR=$HOME/gopath/src/github.com/aframevr/slackoverflow
  - cd $HOME/gopath/src/github.com/aframevr/slackoverflow

install:
  - make dependencies

script:
  - make

cache:
  directories:
    - vendor
